### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Aericio** [GMNetwork/KitPvP#1]
- [ ] Make Messages Configurable

- [ ] Make Kits Configurable

- [ ] Delete Useless Events

- [ ] Use TextFormat instead of Color Codes

- [ ] Remove /kits, make /kit showing the kits, then /kit (kit) gives the kit.

**Comment by SalmonGER** [comment]
I liked the anvil use sound ;(

**Comment by Aericio** [comment]
Make it faster :3

**Comment by Aericio** [comment]
Updated

**Comment by Aericio** [comment]
I might be done with making it into TextFormat... but it got really confusing at some points. Please correct my mistakes @SalmonGER  :+1: :dancer:

**Comment by Aericio** [comment]
@SalmonGER Can you do the auto set kit based on rank thing?
